### PR TITLE
allow access to json response in Assert

### LINKED ISSUE #13: access body after assert
is there a way to access the body json instead of doing an exact assert on it?

in my case I need to assert only on some parts and read others to go on with my test scenario

### PR DESCRIPTION
**Pull request by extrawurst**
closes #13

### CODE REVIEW

**Comment by theredfish** [comment]
Thank you @extrawurst for providing this PR. `Assert` provides everything needed to assert the result, with built-in functions or custom functions (not yet implemented see #7). Ideally we should keep this logic and I would expect `json` to assert a specific json value / body.

In terms of design, the custom function (#7) might be more suited to this need. It must offer the flexibility you need.

We could Implement a function `assert_fn` that takes a closure with an `Assert` parameter. `assert_fn` should return an `Assert` so we can use it multiple times at any moment. I think a good example is the [before](https://cucumber-rs.github.io/cucumber/current/writing/hooks.html#before-hook) function of the cucumber-rs framework. This is what I had in mind until now and you use case seems to match exactly this.

What do you think? If you have time you can implement something similar to that, if not I can work on it. It will certainly takes some time to figure out and maybe move things around. Let me know!

**Comment by extrawurst** [comment]
Can you provide an example how it should look like from a user perspective? I am not sure I get what the intended api should look like :)

**Comment by theredfish** [comment]
Something like that maybe, where you would be able to debug your json response : 

```rust
Grillon::new("http://jsonplaceholder.typicode.com")?
        .get("/users")
        .assert()
        .await
        .status_success()
        .assert_fn(|assert| {
          // an example where you can access the json field
          // but it will need a public visibility.
          println!("Json response : {:#?}", assert.json);
        })
        .status(StatusCode::CREATED)
        .assert_fn(|_assert| {
          println!("Do some stuff without using the assert parameter");
          assert!(true);
        })
        .body(json!({
            "id": 101,
        }));
```

This way we avoid mixing things between built-in functions and accessors while offering some flexibility with custom assertion functions.

There is one caveat though, we don't enforce the generation of assertion error, which slightly modify the intended behavior of `Assert`. And we also make the `json` field public.
But waiting for a better solution, seems like the best way to operate custom stuff and access to the json result.

Maybe there are limitations I don't see right now however. 

The signature of the function should be something like that : 

```rust
    pub fn assert_fn<F>(self, func: F) -> Assert
    where
        F: for<'a> Fn(&'a Assert),
    {
        func(&self);

        self
    }
```

**Comment by theredfish** [comment]
Fixed by #15

**Pull request closed without merging**
